import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom';
import './styles.css';

const phone = '+91 81791 15999';

function Logo(){return <Link className="logo" to="/"><span className="logoMark">E</span><span><b>Eslate</b><small>Technologies</small></span></Link>}
function Header(){const location=useLocation(); return <header><Logo/><nav>{[['/services','Services'],['/career-coaching','Career Coaching'],['/software-projects','Software Projects'],['/about','About']].map(([p,l])=><Link className={location.pathname===p?'active':''} key={p} to={p}>{l}</Link>)}</nav><div className="headerRight"><a href="tel:+918179115999" className="phone">⌕ &nbsp;{phone}</a><Link className="btn small" to="/contact">Contact Us</Link></div></header>}
function Footer(){return <footer><div><Logo/><p>Career guidance, project support and software expertise — accessible to everyone, everywhere.</p></div><div><h4>Explore</h4><Link to="/services">Services</Link><Link to="/career-coaching">Career Coaching</Link><Link to="/software-projects">Software Projects</Link><Link to="/about">About</Link></div><div><h4>Contact</h4><a href="tel:+918179115999">{phone}</a><a href="/contact">Contact us</a></div></footer>}
const Button=({to='/contact',children='Get Started'})=><Link className="btn" to={to}>{children} <span>→</span></Link>;
function Home(){return <><section className="hero"><div className="glow g1"/><div className="glow g2"/><div className="eyebrow">ESLATE TECHNOLOGIES</div><h1>Empowering Careers.<br/>Delivering Projects.<br/>Globally.</h1><p>Eslate Technologies gives students and professionals access to world-class career guidance, project support, and software expertise — from anywhere, for every stage of the journey.</p><div className="actions"><Button to="/services">Explore Services</Button><Link className="textBtn" to="/contact">Contact Us →</Link></div></section><section className="pillars"><div className="sectionHead"><span>WHAT WE DO</span><h2>Three Pillars of Excellence</h2></div><div className="cards three">{[['Career Coaching','Practical guidance to help you build the skills, confidence, and career path that gets results.','/career-coaching'],['Project Support','Hands-on technical support, mentoring, and delivery expertise for real-world projects.','/services'],['Software Development','End-to-end engineering for scalable, modern products built to launch in weeks, not months.','/software-projects']].map(([t,d,p])=><Link className="card" to={p} key={t}><i>↗</i><h3>{t}</h3><p>{d}</p><span>Learn more →</span></Link>)}</div></section><section className="stats"><div><b>500+</b><span>Professionals guided</span></div><div><b>200+</b><span>Projects supported</span></div><div><b>50+</b><span>Global clients</span></div><div><b>10+</b><span>Countries reached</span></div></section></>}
function Services(){return <PageHero eyebrow="OUR SERVICES" title="Expertise that moves you forward." text="From career acceleration to project delivery, Eslate Technologies brings practical expertise and modern engineering together."/><><section className="darkSection"><div className="cards three">{[['Career Coaching','Build a career with clarity, confidence, and a practical roadmap.','Personalized coaching','Interview preparation','Job placement support'],['Project Support','Get experienced technical support to move projects from idea to delivery.','Architecture guidance','Hands-on implementation','Technical mentoring'],['Software Development','Build scalable digital products with a modern engineering team.','Web & mobile applications','Cloud-native systems','AI and automation']].map(x=><div className="card serviceCard" key={x[0]}><div className="icon">✦</div><h3>{x[0]}</h3><p>{x[1]}</p>{x.slice(2).map(a=><div className="check" key={a}>✓ <span>{a}</span></div>)}<Button to={x[0]==='Career Coaching'?'/career-coaching':x[0]==='Software Development'?'/software-projects':'/contact'}>Explore</Button></div>)}</div></section><CTA/></>}
function Career(){return <><PageHero eyebrow="CAREER COACHING" title="Build a career that moves." text="Structured coaching, real-world projects, interview preparation, and placement support for ambitious students and professionals."/><section className="darkSection"><div className="plans"><Plan title="Career Accelerator" old="₹20,000" price="₹9,999" days="45 Days" items={['Playwright fundamentals to advanced automation','GenAI-powered test generation and debugging','MCP server integration and architecture','CI/CD pipeline setup with Playwright','Interview prep and job placement support']}/><Plan featured title="Forward Deployed Engineer" old="₹59,999" price="₹29,999" days="60 Days" items={['Deep-dive into the FDE role at Palantir, Anduril, Scale AI','Client-facing technical project portfolio','FDE interview mastery — technical, case studies, simulations','Personal brand and LinkedIn for FDE recruiters','1-on-1 coaching + placement guarantee']}/></div></section><section className="feature"><div className="eyebrow orange">NEW COURSE · FEATURED PROGRAM</div><h2>Become a Forward Deployed<br/>Engineer</h2><p>Learn to combine engineering depth, customer empathy, and fast execution to solve high-impact problems.</p></section></>}
function Plan({title,old,price,days,items,featured}){return <div className={'plan '+(featured?'featured':'')}><div className="planTop"><span>50% OFF</span><em>{days}</em></div><h3>{title}</h3>{items.map(i=><div className="check" key={i}>✓ <span>{i}</span></div>)}<div className="priceRow"><div><del>{old}</del><strong>{price}</strong></div><div className="duration">Duration<b>{days}</b></div></div><Button>Enroll Now</Button></div>}
function Software(){return <><PageHero eyebrow="SOFTWARE PROJECTS" title="Software that works in the real world." text="From MVPs to production platforms, our engineering teams help you design, build, launch, and scale with confidence."/><section className="darkSection"><div className="cards three">{[['Product Engineering','Modern web and mobile applications, APIs, integrations, and microservices architecture.'],['Cloud & DevOps','Cloud-native infrastructure, CI/CD pipelines, monitoring, and auto-scaling.'],['AI & Automation','Practical AI, workflow automation, and intelligent products designed to launch in weeks, not months.']].map(([t,d])=><div className="card" key={t}><div className="icon">⌘</div><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="tech"><div className="eyebrow orange">TECH STACK</div><h2>Modern Technologies, Proven Results</h2>{[['FRONTEND','React, Next.js, TypeScript, Tailwind CSS'],['BACKEND','Node.js, Python, Java, Go, Express, FastAPI'],['MOBILE','React Native, Flutter, Swift, Kotlin'],['CLOUD','AWS, GCP, Azure, Docker, Kubernetes']].map(([a,b])=><div className="techRow" key={a}><b>{a}</b><span>{b}</span></div>)}</section><CTA/></>}
function About(){return <><PageHero eyebrow="ABOUT US" title={<>Built on Expertise.<br/>Driven by Impact.</>} text="Eslate Technologies was founded with a single mission: to make world-class career guidance and software expertise accessible to everyone, everywhere."/><section className="story"><div><div className="eyebrow orange">OUR STORY</div><h2>From a Vision to a Global Force</h2></div><div><p>Eslate Technologies was born from a simple observation: talented students and professionals around the world were being held back — not by lack of ability, but by lack of access to the right guidance and technology.</p><p>We set out to change that. Starting with career coaching and expanding into project support and full-scale software development, we've grown into a trusted global partner for individuals and organizations across 50+ markets.</p></div></section><section className="values"><div className="eyebrow orange">OUR VALUES</div><h2>What Drives Us</h2><div className="valueGrid">{[['Excellence','We hold ourselves to the highest standards in everything we deliver — no exceptions.'],['Integrity','Honest advice, transparent processes, and relationships built on trust.'],['Global Mindset','We think globally and act locally — understanding the nuances of every market we serve.'],['Empowerment',"We don't just deliver — we equip our clients with the knowledge and tools to keep growing."]].map(([a,b])=><div className="value" key={a}><div className="shield">♢</div><div><h3>{a}</h3><p>{b}</p></div></div>)}</div></section></>}
function Contact(){return <section className="contactPage"><div><div className="eyebrow orange">GET IN TOUCH</div><h1>Let's build what's next.</h1><p>Tell us what you're working on, where you're headed, or what you want to learn. We'll help you find the right next step.</p><div className="contactInfo"><a href="tel:+918179115999">☎ {phone}</a><span>Worldwide · Remote-first</span></div></div><form onSubmit={e=>{e.preventDefault();alert('Thanks! Your enquiry is ready to be connected to your preferred email service.')}}><input placeholder="Your name" required/><input type="email" placeholder="Email address" required/><input placeholder="Phone number"/><select><option>I'm interested in...</option><option>Career Coaching</option><option>Project Support</option><option>Software Development</option></select><textarea placeholder="Tell us a little about your requirement" rows="6"></textarea><button className="btn" type="submit">Send Enquiry →</button></form></section>}
function PageHero({eyebrow,title,text}){return <section className="pageHero"><div className="eyebrow orange">{eyebrow}</div><h1>{title}</h1><p>{text}</p></section>}
function CTA(){return <section className="cta"><div><div className="eyebrow orange">READY WHEN YOU ARE</div><h2>Let's turn the next idea into impact.</h2></div><Button to="/contact">Talk to Eslate</Button></section>}
function App(){return <><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/career-coaching" element={<Career/>}/><Route path="/software-projects" element={<Software/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<Home/>}/></Routes></main><Footer/></>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
